### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by ZiXia1** [yanranxiaoxi/Simplecho#1]
在暗色主题下，从主页进入文章高亮正常，而直接访问文章，则高亮出现问题(灰色)
还有希望后台支持添加pjax回调

**Comment by yanranxiaoxi** [comment]
是想要后台配置页面能够配置 PJAX 加载完成的文字提示，还是说具体什么样的功能

**Comment by ZiXia1** [comment]
pjax回调函数直接在后台添加，免得去修改文件

**Comment by yanranxiaoxi** [comment]
你应该可以直接在“页底：自定义内容”内添加由“<script></script>”包裹的JavaScript代码，就可以免去修改文件啦
我尝试了一下，确实可以直接书写PJAX回调函数并被正确执行

**Comment by yanranxiaoxi** [comment]
代码高亮的问题已经解决了 https://github.com/yanranxiaoxi/Simplecho/commit/485c296ea1bebdf3d96c5dec889d81b3ce172734

如果有不能被正确高亮的代码类型，应该是由于我默认并没有添加太多的代码类型支持，之后我会添加专门的功能用于新增代码类型
