### ISSUE TITLE
经常会失去css样式

### ISSUE THREAD

**Issue by veryxs** [yanranxiaoxi/Simplecho#3]
会间歇性失去css和js样式，看了下当自己网站失去样式时演示站点也一样，更换其他主题正常

**Comment by yanranxiaoxi** [comment]
看起来是 jsDelivr 间歇性无法访问导致的

**Comment by yanranxiaoxi** [comment]
新的提交 https://github.com/yanranxiaoxi/Simplecho/commit/75bd727612005e04cfd371c56aafccf49f51e5b8 解决了这个问题，你有空的话帮助我测试一下，我最近没有什么空闲的时间

感谢

**Comment by yanranxiaoxi** [comment]
已解决 https://github.com/yanranxiaoxi/Simplecho/commit/5202fc14077ca1415ef542d19355f96978f6cdd2
