### ISSUE TITLE
文章界面建议

### ISSUE THREAD

**Issue by imroxe** [yanranxiaoxi/Simplecho#4]
希望作者能在文章页面加个版权声明，这样就不用自己在每篇文章上加这玩意了。

也不知作者还更新不。。。

**Comment by yanranxiaoxi** [comment]
发布了 0.1.15 版本。
现在支持在文章内容的底部新增自定义的 HTML 内容，你可以把你想要的内容编辑好写在这里面，这样所有的文章页都会有这部分内容在底部。

**Comment by imroxe** [comment]
> 发布了 0.1.15 版本。 现在支持在文章内容的底部新增自定义的 HTML 内容，你可以把你想要的内容编辑好写在这里面，这样所有的文章页都会有这部分内容在底部。

你这个并没有在文章底部，而是在首页的顶部，也就是和那个置顶差不多了

![image](https://github.com/user-attachments/assets/6eef668b-2528-4117-a2b4-ba8740f7387d)

**Comment by imroxe** [comment]
还有这两字段有什么用没

![image](https://github.com/user-attachments/assets/64d914b9-b2f5-4448-8bb9-83547e68b23d)

**Comment by yanranxiaoxi** [comment]
> 还有这两字段有什么用没
> 
> ![image](https://private-user-images.githubusercontent.com/34638380/363391975-64d914b9-b2f5-4448-8bb9-83547e68b23d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwODQ2ODMsIm5iZiI6MTcyNTA4NDM4MywicGF0aCI6Ii8zNDYzODM4MC8zNjMzOTE5NzUtNjRkOTE0YjktYjJmNS00NDQ4LThiYjktODM1NDdlNjhiMjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDA2MDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNTU2MGQ1MmJhNjk3ODc1MjVkYzkzNjMwYjVlOTk5YTM2ZDgxOTk2MTg2MGI4MmU3OWFhN2Y5ZDc2Y2E4OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uPANen5z6d9RyVs-9VyOI6o9mNmx5Y9yzL6L_RANtfE)

会出现在 SEO 内容内，即 meta 属性

**Comment by oaxao** [comment]
![image](https://github.com/user-attachments/assets/13f8b738-fc82-4019-a2ea-935a746d237c)

这个复制粘贴，其实typecho原本就有吧，在`\admin\editor-js.php`中

![image](https://github.com/user-attachments/assets/72015091-ba5d-4521-8f8a-f46d5c3e3a0b)
