### ISSUE TITLE
[BUG] 评论界面有问题

### ISSUE THREAD

**Issue by imroxe** [yanranxiaoxi/Simplecho#5]
Typecho版本：1.2.1

复现：
1、typecho后台开启评论审核
![image](https://github.com/user-attachments/assets/d709cf44-3c26-4eaf-8695-04f901d30879)

2、前台找篇文章用游客身份评论
![image](https://github.com/user-attachments/assets/37e9ff3c-44e0-4e6d-aff6-7d4221ca527e)

3、刷新该页面
![image](https://github.com/user-attachments/assets/8c241bbc-8370-4e92-837f-82f4e49c199b)

上面其实是少了个_mt()函数，该函数是在functions.php里面调用了，二改的作者源码也没写这个函数，issue里也有人提到这个问题
![image](https://github.com/user-attachments/assets/c4474356-a1a3-4747-81ca-3ac3634c840a)

额外建议：
1、希望能加个自动深色功能。就一到晚上自动换成暗夜黒，白天换成原主题。

感谢！感谢！

**Comment by yanranxiaoxi** [comment]
@oaxao 感觉自动深色应该不通过主题来配置，而是通过系统或者浏览器配置

我可以在主题内添加跟随浏览器主题的功能
