### ISSUE TITLE
复制粘贴是原来的不好用么？

### ISSUE THREAD

**Issue by imroxe** [yanranxiaoxi/Simplecho#6]
![image](https://github.com/user-attachments/assets/13f8b738-fc82-4019-a2ea-935a746d237c)

## 这个复制粘贴，其实typecho原本就有吧，在`\admin\editor-js.php`中

![image](https://github.com/user-attachments/assets/72015091-ba5d-4521-8f8a-f46d5c3e3a0b)

## 加了之后就重复上传了，不过文件大小不一样，你这样上传的文件小点

![image](https://github.com/user-attachments/assets/deae2579-3eea-4f65-a0e8-90bf477186c0)

**Comment by yanranxiaoxi** [comment]
主要是解决以前预览不更新的问题，不过现在应该属于冗余了
